# Generated by Django 5.1.15 on 2026-06-03 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_PAUSE', 'En pause'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin prévue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Direction')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('team', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Couleur')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projects.project')),
            ],
            options={
                'verbose_name': 'Epic',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('goal', models.TextField(blank=True, verbose_name='Objectif')),
                ('status', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('ACTIF', 'Actif'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=15, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project')),
            ],
            options={
                'verbose_name': 'Sprint',
                'ordering': ['project', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('acceptance_criteria', models.TextField(blank=True, verbose_name="Critères d'acceptation")),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('IN_TEST', 'En test'), ('DONE', 'Terminé')], default='BACKLOG', max_length=15, verbose_name='Statut')),
                ('story_points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorité')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to='projects.epic')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stories', to='projects.sprint')),
            ],
            options={
                'verbose_name': 'User Story',
                'verbose_name_plural': 'User Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], default='TODO', max_length=15, verbose_name='Statut')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures estimées')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures réelles')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.userstory')),
            ],
            options={
                'verbose_name': 'Tâche',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
