# Generated by Django 5.1.15 on 2026-06-07 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text="Membre IT chargé de créer les tâches et suivre l'exécution.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name="Responsable d'exécution"),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Chef de projet'),
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('status', models.CharField(choices=[('ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVRE', 'Livré'), ('VALIDE', 'Validé')], default='ATTENTE', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables', to='projects.sprint', verbose_name='Sprint associé')),
            ],
            options={
                'verbose_name': 'Livrable',
                'verbose_name_plural': 'Livrables',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
