# Generated by Django 5.1.15 on 2026-06-05 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Responsable de la distribution des tickets dans ce département (hors IT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL, verbose_name='Manager ticketing'),
        ),
        migrations.AddField(
            model_name='department',
            name='ticketing_enabled',
            field=models.BooleanField(default=False, help_text="Ce département peut recevoir des tickets depuis d'autres départements. Activez uniquement après accord contractuel. Le département Informatique est toujours actif par défaut.", verbose_name='Ticketing activé'),
        ),
    ]
