# Generated by Django 5.1.15 on 2026-06-07 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_manager_department_ticketing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Code de confirmation'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirm_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code envoyé le'),
        ),
        migrations.CreateModel(
            name='AuthorizedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.CharField(max_length=50, unique=True, verbose_name='CUID')),
                ('employee_status', models.CharField(choices=[('permanent', 'Permanent'), ('interimaire', 'Intérimaire'), ('stagiaire', 'Stagiaire'), ('temporaire', 'Temporaire')], default='permanent', max_length=20, verbose_name='Statut')),
                ('is_registered', models.BooleanField(default=False, verbose_name='Inscrit')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Chargé le')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_employees', to='accounts.department', verbose_name='Département')),
                ('registered_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_employee', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé autorisé',
                'verbose_name_plural': 'Employés autorisés',
                'ordering': ['cuid'],
            },
        ),
    ]
