# Generated by Django 5.1.15 on 2026-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email_confirm_code_user_email_confirm_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_project_manager',
            field=models.BooleanField(default=False, help_text='Permet de créer et piloter des projets (en plus du rôle principal).', verbose_name='Chef de projet IT'),
        ),
    ]
