# Generated by Django 5.1.15 on 2026-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_project_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd_reset_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Code reset MDP'),
        ),
        migrations.AddField(
            model_name='user',
            name='pwd_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Code reset envoyé le'),
        ),
    ]
