# Generated by Django 5.1.15 on 2026-07-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_pwd_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text="Département de transit pour les utilisateurs SSO sans affectation. Les membres ne voient que leurs propres tickets. Affecter un département réel via l'admin utilisateur.", verbose_name='Département provisoire'),
        ),
    ]
