# Generated by Django 5.1.15 on 2026-06-03 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='bi-book', max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='primary', max_length=30, verbose_name='Couleur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie KB',
                'verbose_name_plural': 'Catégories KB',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FAQ', 'FAQ'), ('PROCEDURE', 'Procédure'), ('GUIDE', 'Guide utilisateur'), ('SOLUTION', 'Solution récurrente')], default='FAQ', max_length=15, verbose_name='Type')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='Résumé')),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500, verbose_name='Tags')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('visibility_restricted', models.BooleanField(default=False, help_text='Si coché, seuls les départements sélectionnés peuvent voir cet article.', verbose_name='Visibilité restreinte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL)),
                ('related_tickets', models.ManyToManyField(blank=True, related_name='kb_articles', to='tickets.ticket', verbose_name='Tickets liés')),
                ('visible_to_departments', models.ManyToManyField(blank=True, related_name='kb_articles', to='accounts.department', verbose_name='Visible par les départements')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledge_base.kbcategory')),
            ],
            options={
                'verbose_name': 'Article',
                'ordering': ['-created_at'],
            },
        ),
    ]
