# Generated by Django 5.1.15 on 2026-06-03 21:31

import apps.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCIDENT', 'Incident'), ('EVOLUTION', "Demande d'Évolution"), ('SUPPORT', 'Support Fonctionnel'), ('PONCTUEL', 'Demande Ponctuelle'), ('TACHE_PROJET', 'Tâche Projet')], max_length=20, unique=True, verbose_name='Type')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(default='bi-ticket', max_length=50, verbose_name='Icône Bootstrap')),
                ('color', models.CharField(default='primary', max_length=30, verbose_name='Couleur CSS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('P0', 'P0 - Critique'), ('P1', 'P1 - Haute'), ('P2', 'P2 - Moyenne'), ('P3', 'P3 - Faible')], max_length=5, unique=True, verbose_name='Priorité')),
                ('response_time_minutes', models.PositiveIntegerField(default=30, help_text='Temps maximal avant la première prise en charge.', verbose_name='Délai prise en charge (min)')),
                ('resolution_time_minutes', models.PositiveIntegerField(default=480, help_text='Temps maximal avant résolution.', verbose_name='Délai de traitement (min)')),
            ],
            options={
                'verbose_name': 'Configuration SLA',
                'verbose_name_plural': 'Configurations SLA',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.department', verbose_name='Département propriétaire')),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tickets.category')),
            ],
            options={
                'verbose_name': 'Sous-catégorie',
                'verbose_name_plural': 'Sous-catégories',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('P0', 'P0 - Critique'), ('P1', 'P1 - Haute'), ('P2', 'P2 - Moyenne'), ('P3', 'P3 - Faible')], default='P2', max_length=5, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('AFFECTE', 'Affecté'), ('EN_COURS', 'En cours'), ('ATTENTE_INFO', "En attente d'information"), ('ATTENTE_PRESTATAIRE', 'En attente prestataire'), ('RESOLU', 'Résolu'), ('CLOTURE', 'Clôturé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='NOUVEAU', max_length=25, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Pris en charge le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturé le')),
                ('sla_response_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Échéance prise en charge')),
                ('sla_resolution_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Échéance traitement')),
                ('sla_response_exceeded', models.BooleanField(default=False, verbose_name='Prise en charge hors délai')),
                ('sla_resolution_exceeded', models.BooleanField(default=False, verbose_name='Traitement hors délai')),
                ('resolved_out_of_sla', models.BooleanField(default=False, verbose_name='Résolu hors SLA')),
                ('sla_paused_at', models.DateTimeField(blank=True, null=True, verbose_name='SLA mis en pause le')),
                ('sla_pause_minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes de pause SLA accumulées')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.application', verbose_name='Application')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.category', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.department', verbose_name='Département')),
                ('info_requested_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_requested_tickets', to=settings.AUTH_USER_MODEL, verbose_name="Demande d'info à")),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='projects.project', verbose_name='Projet')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.subcategory', verbose_name='Sous-catégorie')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_tickets', to='accounts.department', verbose_name='Département cible')),
            ],
            options={
                'verbose_name': 'Ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Commentaire interne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tickets.models.ticket_attachment_path, verbose_name='Fichier')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Taille')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Type MIME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='Champ')),
                ('old_value', models.TextField(blank=True, verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'ordering': ['-created_at'],
            },
        ),
    ]
