# ══════════════════════════════════════════════════════════════════════════════
# PersistentVolumeClaim — stockage des pièces jointes (media)
# StorageClass par défaut CRC : crc-csi-hostpath-provisioner
# ══════════════════════════════════════════════════════════════════════════════
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ittis-media
  namespace: ittis
  labels:
    app.kubernetes.io/name: ittis
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: crc-csi-hostpath-provisioner
  resources:
    requests:
      storage: 5Gi
